name: CVML
channels:
  - conda-forge
  - defaults
dependencies:
  - opencv
  - pandas
  - ipython
  - matplotlib
  - seaborn
  - scikit-learn
  - spyder
  - notebook
  - scikit-image
  - tabulate
  - scikit-spatial
  - jupyterlab
  - voila
  - ca-certificates
  - certifi
  - openssl
  - ipympl
  - jupyterlab-link-share
  - pysindy
  - tikzplotlib
  - stochastic
  - wandb
  - wand
  - jax
  - nbconvert-webpdf
  - jupyterlab-markup
  - sympy
  - spyder-notebook
  - cvxpy
  - autograd
  - nodejs
  - jaxopt
